### PR TITLE
Updated pydantic version to 2.10.6 (<2.10.2 failing)

### LINKED ISSUE #1316: [Bug]: Pydantic version compatibility
### Describe the bug

When using pydantic version < v2.10.2, 
I get this error:
```
    from pydantic._internal._typing_extra import try_eval_type  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'try_eval_type' from 'pydantic._internal._typing_extra' (.../site-packages/pydantic/_internal/_typing_extra.py). Did you mean: '_eval_type'?
```  
https://github.com/ag2ai/ag2/blob/main/autogen/tools/function_utils.py#L14

### Steps to reproduce

- Install pydantic<2.10.2 (`python -m pip install pydantic<2.10.2`) 
- Install ag2 (`python -m pip install ag2`)
- Try to import autogen (`python -c 'import autogen'`).

### Model Used

_No response_

### Expected Behavior

Not to raise an ImportError.

### Screenshots and logs

_No response_

### Additional Information

Changing the minimum pydantic version in pyproject.toml (to >=2.10.2, ref: https://github.com/pydantic/pydantic/blob/v2.10.2/pydantic/_internal/_typing_extra.py#L538) could fix this issue, but I don't know if this change would break something else.

### PR DESCRIPTION
**Pull request by marklysze**
## Why are these changes needed?

@lazToum noted that Pydantic versions < 2.10.2 are failing (from `autogen/tools/function_utils.py`):
```
from pydantic._internal._typing_extra import try_eval_type  # type: ignore[attr-defined]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'try_eval_type' from 'pydantic._internal._typing_extra' (.../site-packages/pydantic/_internal/_typing_extra.py). Did you mean: '_eval_type'?
```

This updates to the current version, which doesn't throw this exception.

## Related issue number

Closes #1316

## Checks

- [ ] I've included any doc changes needed for https://docs.ag2.ai/. See https://docs.ag2.ai/docs/contributor-guide/documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by davorrunje** [comment]
I would rather keep Pydantic version less restricted as it is required by many other packages. I fixed the issue in a way to work with version less and greater than 2.10.2 in #1356
